import Foundation
import XCTest
@testable import PocketContracts

#if canImport(CryptoKit)
import CryptoKit

final class VerifiedActionReceiptTests: XCTestCase {
    private let createdAt = Date(timeIntervalSince1970: 1_752_835_200)

    private func base64url(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    private func keySource(
        _ key: Curve25519.Signing.PrivateKey,
        id: String = "receipt-key-v1",
        purposes: Set<PocketGatewaySigningPurpose> = [.actionReceipt]
    ) -> PocketGatewaySigningKey {
        let raw = key.publicKey.rawRepresentation
        return PocketGatewaySigningKey(
            signingKeyId: id,
            publicKeyBase64url: base64url(raw),
            publicKeySHA256Base64url: base64url(Data(SHA256.hash(data: raw))),
            purposes: purposes
        )
    }

    private func proposal(
        id: String = "proposal-1",
        kind: ActionKind = .humanMessage,
        targetSessionId: String = "session-1",
        targetSequence: Int? = nil
    ) -> ActionProposal {
        ActionProposal(
            id: id,
            kind: kind,
            targetSessionId: targetSessionId,
            targetSequence: targetSequence ?? (kind == .humanMessage ? 0 : 42),
            renderedPreview: "approved words",
            createdAt: createdAt,
            sourceQuestionId: nil
        )
    }

    private func confirmation(
        for proposal: ActionProposal,
        proposalId: String? = nil,
        hash: String? = nil,
        at: Date? = nil
    ) -> GovernedWriteConfirmation {
        GovernedWriteConfirmation(
            proposalId: proposalId ?? proposal.id,
            confirmedProposalHash: hash ?? proposal.proposalHash,
            confirmedAt: at ?? createdAt.addingTimeInterval(1)
        )
    }

    private func signedReceipt(
        proposal: ActionProposal,
        confirmation: GovernedWriteConfirmation,
        key: Curve25519.Signing.PrivateKey,
        signingKeyId: String = "receipt-key-v1",
        receiptId: String? = nil,
        proposalId: String? = nil,
        targetSessionId: String? = nil,
        confirmedProposalHash: String? = nil,
        confirmedAt: Date? = nil,
        executedAt: Date? = nil,
        result: ActionResultRef? = nil
    ) throws -> ActionReceipt {
        let resolvedResult: ActionResultRef = result ?? (proposal.kind == .humanMessage
            ? .sequence(sequenceId: 9001)
            : .action(actionId: "action-1", targetSequenceId: proposal.targetSequence, targetCursor: "cursor-1"))
        let unsigned = ActionReceipt(
            id: receiptId ?? proposal.id,
            proposalId: proposalId ?? proposal.id,
            status: .posted,
            result: resolvedResult,
            targetSessionId: targetSessionId ?? proposal.targetSessionId,
            confirmedByHumanAt: confirmedAt ?? confirmation.confirmedAt,
            confirmedProposalHash: confirmedProposalHash ?? proposal.proposalHash,
            executedAt: executedAt ?? confirmation.confirmedAt.addingTimeInterval(1),
            failureReason: nil,
            signature: "placeholder",
            signingKeyId: signingKeyId
        )
        let signature = try key.signature(for: Data(unsigned.canonicalReceiptPayload().utf8))
        return ActionReceipt(
            id: unsigned.id,
            proposalId: unsigned.proposalId,
            status: unsigned.status,
            result: unsigned.result,
            targetSessionId: unsigned.targetSessionId,
            confirmedByHumanAt: unsigned.confirmedByHumanAt,
            confirmedProposalHash: unsigned.confirmedProposalHash,
            executedAt: unsigned.executedAt,
            failureReason: nil,
            signature: base64url(signature),
            signingKeyId: unsigned.signingKeyId
        )
    }

    func testProductionReceiptTrustIsEmptyAndDemoBundleKeysArePurposeSeparated() {
        XCTAssertFalse(PocketGatewaySigningKeyRegistry.production.hasKey(for: .actionReceipt))
        XCTAssertNotNil(PocketGatewaySigningKeyRegistry.production.rawPublicKey(
            signingKeyId: PocketDemoGatewayKey.signingKeyId,
            purpose: .bundle
        ))
        XCTAssertNil(PocketGatewaySigningKeyRegistry.production.rawPublicKey(
            signingKeyId: PocketDemoGatewayKey.signingKeyId,
            purpose: .actionReceipt
        ))
    }

    /// Cross-language KAV generated by Node's `computeProposalHash` + `signReceipt` from the fixed test-only
    /// Ed25519 seed `b2` x 32. The Swift admission path must reproduce the proposal hash and verify Node's exact
    /// signature; mutating a signature-bound but proposal-independent field must fail with the same 64-byte signature.
    func testNodeGeneratedKnownAnswerReceiptMintsAndValidLengthTamperFails() {
        let proposal = ActionProposal(
            id: "proposal-kav-1",
            kind: .humanMessage,
            targetSessionId: "session-kav-1",
            targetSequence: 0,
            renderedPreview: "KAV confirmed words",
            createdAt: Date(timeIntervalSince1970: 1_786_622_400),
            sourceQuestionId: nil
        )
        XCTAssertEqual(proposal.proposalHash, "4-UodR6Is9ZWn9Hna4RdGVk_m96c5cbcBeKNqQQjqPw")
        let confirmation = GovernedWriteConfirmation(
            proposalId: proposal.id,
            confirmedProposalHash: proposal.proposalHash,
            confirmedAt: Date(timeIntervalSince1970: 1_786_622_401)
        )
        let receipt = ActionReceipt(
            id: "receipt-kav-1",
            proposalId: proposal.id,
            status: .posted,
            result: .sequence(sequenceId: 123),
            targetSessionId: proposal.targetSessionId,
            confirmedByHumanAt: confirmation.confirmedAt,
            confirmedProposalHash: proposal.proposalHash,
            executedAt: Date(timeIntervalSince1970: 1_786_622_402),
            failureReason: nil,
            signature: "KXxzIrQZU0ranXULcSXtuyeB3yjP4eGU2pIj8zxHjIV2TMmctImB-9bcbv2TnbGo-oU-w-DgJ_RSBGmwwz10Dg",
            signingKeyId: "receipt-kav-key-v1"
        )
        let registry = PocketGatewaySigningKeyRegistry(keys: [PocketGatewaySigningKey(
            signingKeyId: "receipt-kav-key-v1",
            publicKeyBase64url: "VRVPQgZepaG-oFRjgmviaE65LfksEAAnqrquV8pVQgc",
            publicKeySHA256Base64url: "souqsz4flaeMfpVHVUw-laLjgDCixkzkU3jxXTOk3dY",
            purposes: [.actionReceipt]
        )])

        XCTAssertNotNil(VerifiedActionReceipt.verify(
            receipt,
            for: proposal,
            confirmation: confirmation,
            registry: registry
        ))

        let tamperedReceiptIdentity = ActionReceipt(
            id: "receipt-kav-2",
            proposalId: receipt.proposalId,
            status: receipt.status,
            result: receipt.result,
            targetSessionId: receipt.targetSessionId,
            confirmedByHumanAt: receipt.confirmedByHumanAt,
            confirmedProposalHash: receipt.confirmedProposalHash,
            executedAt: receipt.executedAt,
            failureReason: receipt.failureReason,
            signature: receipt.signature,
            signingKeyId: receipt.signingKeyId
        )
        XCTAssertNil(VerifiedActionReceipt.verify(
            tamperedReceiptIdentity,
            for: proposal,
            confirmation: confirmation,
            registry: registry
        ))
    }

    func testValidIndependentReceiptIdentityMintsOnlyThroughExactCompiledRegistryEntry() throws {
        let privateKey = Curve25519.Signing.PrivateKey()
        let registry = PocketGatewaySigningKeyRegistry(keys: [keySource(privateKey)])
        let proposal = proposal()
        let confirmation = confirmation(for: proposal)
        let receipt = try signedReceipt(
            proposal: proposal,
            confirmation: confirmation,
            key: privateKey,
            receiptId: "server-receipt-9"
        )

        let verified = VerifiedActionReceipt.verify(
            receipt,
            for: proposal,
            confirmation: confirmation,
            registry: registry
        )

        XCTAssertEqual(verified?.receipt, receipt)
        XCTAssertEqual(verified?.result, .sequence(sequenceId: 9001))
        XCTAssertEqual(verified?.signingKeyId, "receipt-key-v1")
        XCTAssertNil(
            VerifiedActionReceipt.verify(receipt, for: proposal, confirmation: confirmation),
            "the production overload must remain fail-closed until reviewed receipt anchors are compiled"
        )
    }

    func testReceiptAdmissionRejectsEveryLocalBindingAndTimelineSubstitution() throws {
        let privateKey = Curve25519.Signing.PrivateKey()
        let registry = PocketGatewaySigningKeyRegistry(keys: [keySource(privateKey)])
        let proposal = proposal()
        let confirmation = confirmation(for: proposal)
        let composed = "proposal-caf\u{00e9}"
        let decomposed = "proposal-cafe\u{0301}"
        let unicodeProposal = self.proposal(id: composed)
        let unicodeConfirmation = self.confirmation(for: unicodeProposal)
        let earlyConfirmation = self.confirmation(
            for: proposal,
            at: createdAt.addingTimeInterval(-1)
        )

        let substitutions = [
            try signedReceipt(proposal: proposal, confirmation: confirmation, key: privateKey, receiptId: ""),
            try signedReceipt(
                proposal: proposal,
                confirmation: confirmation,
                key: privateKey,
                receiptId: String(repeating: "r", count: 257)
            ),
            try signedReceipt(proposal: proposal, confirmation: confirmation, key: privateKey, proposalId: "other"),
            try signedReceipt(proposal: proposal, confirmation: confirmation, key: privateKey, targetSessionId: "other"),
            try signedReceipt(proposal: proposal, confirmation: confirmation, key: privateKey, confirmedProposalHash: "other"),
            try signedReceipt(
                proposal: proposal,
                confirmation: confirmation,
                key: privateKey,
                confirmedAt: confirmation.confirmedAt.addingTimeInterval(0.001)
            ),
            try signedReceipt(
                proposal: proposal,
                confirmation: confirmation,
                key: privateKey,
                executedAt: confirmation.confirmedAt.addingTimeInterval(-0.001)
            ),
        ]

        for receipt in substitutions {
            XCTAssertNil(VerifiedActionReceipt.verify(
                receipt,
                for: proposal,
                confirmation: confirmation,
                registry: registry
            ))
        }

        let unicodeAlias = try signedReceipt(
            proposal: unicodeProposal,
            confirmation: unicodeConfirmation,
            key: privateKey,
            receiptId: "receipt-unicode",
            proposalId: decomposed
        )
        XCTAssertNil(VerifiedActionReceipt.verify(
            unicodeAlias,
            for: unicodeProposal,
            confirmation: unicodeConfirmation,
            registry: registry
        ))

        let valid = try signedReceipt(proposal: proposal, confirmation: confirmation, key: privateKey)
        XCTAssertNil(VerifiedActionReceipt.verify(
            valid,
            for: proposal,
            confirmation: self.confirmation(for: proposal, proposalId: "other"),
            registry: registry
        ))
        XCTAssertNil(VerifiedActionReceipt.verify(
            valid,
            for: proposal,
            confirmation: self.confirmation(for: proposal, hash: "other"),
            registry: registry
        ))

        let earlyReceipt = try signedReceipt(
            proposal: proposal,
            confirmation: earlyConfirmation,
            key: privateKey
        )
        XCTAssertNil(VerifiedActionReceipt.verify(
            earlyReceipt,
            for: proposal,
            confirmation: earlyConfirmation,
            registry: registry
        ), "a confirmation before the proposal was created must never admit its receipt")

        let equalityBoundaryConfirmation = self.confirmation(for: proposal, at: proposal.createdAt)
        let equalityBoundaryReceipt = try signedReceipt(
            proposal: proposal,
            confirmation: equalityBoundaryConfirmation,
            key: privateKey,
            executedAt: proposal.createdAt
        )
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            equalityBoundaryReceipt,
            for: proposal,
            confirmation: equalityBoundaryConfirmation,
            registry: registry
        ))
    }

    func testReceiptAdmissionRejectsUnknownKeyBadSignatureAndWrongResultShape() throws {
        let privateKey = Curve25519.Signing.PrivateKey()
        let registry = PocketGatewaySigningKeyRegistry(keys: [keySource(privateKey)])
        let humanProposal = proposal()
        let humanConfirmation = confirmation(for: humanProposal)
        let threadedProposal = proposal(id: "threaded-proposal", kind: .threadedReply)
        let threadedConfirmation = confirmation(for: threadedProposal)
        let opinionProposal = proposal(id: "opinion-proposal", kind: .opinionRequest)
        let opinionConfirmation = confirmation(for: opinionProposal)

        let unknownKey = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            signingKeyId: "unknown-key"
        )
        XCTAssertNil(VerifiedActionReceipt.verify(
            unknownKey,
            for: humanProposal,
            confirmation: humanConfirmation,
            registry: registry
        ))

        let valid = try signedReceipt(proposal: humanProposal, confirmation: humanConfirmation, key: privateKey)
        let bundleOnlyRegistry = PocketGatewaySigningKeyRegistry(keys: [keySource(
            privateKey,
            purposes: [.bundle]
        )])
        XCTAssertNil(VerifiedActionReceipt.verify(
            valid,
            for: humanProposal,
            confirmation: humanConfirmation,
            registry: bundleOnlyRegistry
        ), "a cryptographically valid bundle-purpose key must not authenticate an action receipt")
        let badSignature = ActionReceipt(
            id: valid.id,
            proposalId: valid.proposalId,
            status: valid.status,
            result: valid.result,
            targetSessionId: valid.targetSessionId,
            confirmedByHumanAt: valid.confirmedByHumanAt,
            confirmedProposalHash: valid.confirmedProposalHash,
            executedAt: valid.executedAt,
            failureReason: valid.failureReason,
            signature: "AA",
            signingKeyId: valid.signingKeyId
        )
        XCTAssertNil(VerifiedActionReceipt.verify(
            badSignature,
            for: humanProposal,
            confirmation: humanConfirmation,
            registry: registry
        ))

        let actionForHuman = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            result: .action(actionId: "action-1", targetSequenceId: 1, targetCursor: nil)
        )
        let sequenceForThread = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: 1)
        )
        let wrongThreadTarget = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(actionId: "action-1", targetSequenceId: 43, targetCursor: nil)
        )
        let oversizedCursor = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(actionId: "action-1", targetSequenceId: 42, targetCursor: String(repeating: "x", count: 257))
        )
        let unsafeSequence = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: 9_007_199_254_740_992)
        )
        let zeroSequence = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: 0)
        )
        let negativeSequence = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: -1)
        )
        let emptyActionId = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(actionId: "", targetSequenceId: 42, targetCursor: nil)
        )
        let oversizedActionId = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(
                actionId: String(repeating: "a", count: 257),
                targetSequenceId: 42,
                targetCursor: nil
            )
        )
        let opinionSequence = try signedReceipt(
            proposal: opinionProposal,
            confirmation: opinionConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: 1)
        )
        let rejectedCases: [(ActionReceipt, ActionProposal, GovernedWriteConfirmation)] = [
            (actionForHuman, humanProposal, humanConfirmation),
            (unsafeSequence, humanProposal, humanConfirmation),
            (zeroSequence, humanProposal, humanConfirmation),
            (negativeSequence, humanProposal, humanConfirmation),
            (sequenceForThread, threadedProposal, threadedConfirmation),
            (wrongThreadTarget, threadedProposal, threadedConfirmation),
            (oversizedCursor, threadedProposal, threadedConfirmation),
            (emptyActionId, threadedProposal, threadedConfirmation),
            (oversizedActionId, threadedProposal, threadedConfirmation),
            (opinionSequence, opinionProposal, opinionConfirmation),
        ]
        for (receipt, boundProposal, boundConfirmation) in rejectedCases {
            XCTAssertNil(VerifiedActionReceipt.verify(
                receipt,
                for: boundProposal,
                confirmation: boundConfirmation,
                registry: registry
            ))
        }

        let maximumSafeSequence = try signedReceipt(
            proposal: humanProposal,
            confirmation: humanConfirmation,
            key: privateKey,
            result: .sequence(sequenceId: 9_007_199_254_740_991)
        )
        let emptyCursor = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(actionId: "action-1", targetSequenceId: 42, targetCursor: "")
        )
        let maximumBoundedAction = try signedReceipt(
            proposal: threadedProposal,
            confirmation: threadedConfirmation,
            key: privateKey,
            result: .action(
                actionId: String(repeating: "a", count: 256),
                targetSequenceId: 42,
                targetCursor: String(repeating: "c", count: 256)
            )
        )
        let opinionAction = try signedReceipt(
            proposal: opinionProposal,
            confirmation: opinionConfirmation,
            key: privateKey,
            result: .action(actionId: "opinion-action", targetSequenceId: 42, targetCursor: nil)
        )
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            maximumSafeSequence,
            for: humanProposal,
            confirmation: humanConfirmation,
            registry: registry
        ))
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            emptyCursor,
            for: threadedProposal,
            confirmation: threadedConfirmation,
            registry: registry
        ))
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            maximumBoundedAction,
            for: threadedProposal,
            confirmation: threadedConfirmation,
            registry: registry
        ))
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            opinionAction,
            for: opinionProposal,
            confirmation: opinionConfirmation,
            registry: registry
        ))
    }

    func testRegistryFailsClosedAsAUnitAndSupportsExplicitRotationOverlap() throws {
        let oldKey = Curve25519.Signing.PrivateKey()
        let newKey = Curve25519.Signing.PrivateKey()
        let oldSource = keySource(oldKey, id: "receipt-key-old")
        let newSource = keySource(newKey, id: "receipt-key-new")
        let rotation = PocketGatewaySigningKeyRegistry(keys: [oldSource, newSource])
        XCTAssertTrue(rotation.isStructurallyValid)
        XCTAssertTrue(rotation.hasKey(for: .actionReceipt))
        XCTAssertNotNil(rotation.rawPublicKey(signingKeyId: "receipt-key-old", purpose: .actionReceipt))

        let proposal = proposal()
        let confirmation = confirmation(for: proposal)
        for (key, id) in [(oldKey, "receipt-key-old"), (newKey, "receipt-key-new")] {
            let receipt = try signedReceipt(
                proposal: proposal,
                confirmation: confirmation,
                key: key,
                signingKeyId: id
            )
            XCTAssertNotNil(VerifiedActionReceipt.verify(
                receipt,
                for: proposal,
                confirmation: confirmation,
                registry: rotation
            ))
        }

        let oldReceipt = try signedReceipt(
            proposal: proposal,
            confirmation: confirmation,
            key: oldKey,
            signingKeyId: "receipt-key-old"
        )
        let newReceipt = try signedReceipt(
            proposal: proposal,
            confirmation: confirmation,
            key: newKey,
            signingKeyId: "receipt-key-new"
        )
        let newOnly = PocketGatewaySigningKeyRegistry(keys: [newSource])
        XCTAssertTrue(newOnly.isStructurallyValid)
        XCTAssertNotNil(VerifiedActionReceipt.verify(
            newReceipt,
            for: proposal,
            confirmation: confirmation,
            registry: newOnly
        ))
        XCTAssertNil(VerifiedActionReceipt.verify(
            oldReceipt,
            for: proposal,
            confirmation: confirmation,
            registry: newOnly
        ), "retiring an old key id must make its otherwise-valid receipt unverifiable")

        let duplicate = PocketGatewaySigningKeyRegistry(keys: [oldSource, oldSource])
        XCTAssertFalse(duplicate.isStructurallyValid)
        XCTAssertNil(duplicate.rawPublicKey(signingKeyId: oldSource.signingKeyId, purpose: .actionReceipt))

        let badFingerprint = PocketGatewaySigningKey(
            signingKeyId: "receipt-key-bad",
            publicKeyBase64url: oldSource.publicKeyBase64url,
            publicKeySHA256Base64url: "AA",
            purposes: [.actionReceipt]
        )
        let invalid = PocketGatewaySigningKeyRegistry(keys: [newSource, badFingerprint])
        XCTAssertFalse(invalid.isStructurallyValid)
        XCTAssertNil(invalid.rawPublicKey(signingKeyId: newSource.signingKeyId, purpose: .actionReceipt))
    }
}
#endif
